theme: osuny
_merge: deep
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site
  posts:
    index:
      layout: grid
      options:
        image: false
        reading_time: true